#!/bin/sh -e

# load our vars
. $HOME/agno/agnorc || exit 1
. ./Pkgfile || exit 1

# re-define vars with new info
PKGNAME=$name\#$version-$release
AGNO_SOURCE=$AGNO_SOURCE/$PKGNAME
AGNO_DESTDIR=$AGNO_DESTDIR/$PKGNAME

# download source files (if necessary)
if [ -n "$source" ]; then
	mkdir -p $AGNO_SOURCE
	cd $AGNO_SOURCE
	for url in $source; do
		# only download stuff that looks like a URL
		if grep -qE '^(http|ftp)s?://'; then
			curl --ssl -L -O $url
		fi
	done
fi

# create necessary dirs for build
mkdir -p $AGNO_DESTDIR $AGNO_WORK

# unpack / copy source files if there are any
if [ -n "$(ls $AGNO_SOURCE)" ]; then
	$AGNO_HOME/unboop *
	cp -R $AGNO_SOURCE/* $AGNO_WORK
fi

# run build function
cd $AGNO_WORK
agno_build

# gotta install that shiz diz
agno_install

# let's make a package out of the result
cd $AGNO_DESTDIR
tar -czv . > $AGNO_PACKAGES/$PKGNAME.tar.gz 

# we're done! let's cleanup
rm -rf $AGNO_WORK $AGNO_DESTDIR

# notice
echo "Built '$PKGNAME' successfully (i.e. without errors)"
