#!/bin/sh -e

# load our vars
. $HOME/agno/agnorc || exit 1
. ./Pkgfile || exit 1

PKGFILE_DIR=$PWD

# re-define vars with new info
PKGNAME=$name\#$version-$release
AGNO_SOURCE=$AGNO_SOURCE/$PKGNAME
AGNO_DESTDIR=$AGNO_DESTDIR/$PKGNAME
AGNO_WORK=$AGNO_WORK/$PKGNAME

# download source files (if necessary)
if [ -n "$source" ]; then
	test -d $AGNO_SOURCE || mkdir -p $AGNO_SOURCE
	cd $AGNO_SOURCE

	# loop through our sources
	for src in $source; do
		# looks like a URL, want to download this
		if echo $src | grep -qE '^(http|ftp)s?://'; then
			# if file by the same name doesn't exist
			if [ ! -e "${src##*/}" ]; then
				curl --ssl -L -O $src
			else
				echo "Skipping download of '$src'."
			fi
		# looks like git, we want to handle this differently
		elif echo $src | grep -qE '^git://'; then
			# if we've already got a dir by that name
			if cd $name-git; then
				# reset state of local repo
				git fetch -q
				git reset --hard origin/master
			else
				# don't clone the whole thing, we don't need it
				git clone --depth 1 $src $name-git
			fi
		# we've got ourselves a normal file
		else
			cp -fR $PKGFILE_DIR/$src $AGNO_SOURCE
		fi
	done
fi

# reset/create necessary dirs for build
rm -rf $AGNO_DESTDIR $AGNO_WORK
mkdir -p $AGNO_DESTDIR $AGNO_WORK

# unpack / copy source files if there are any
if [ -n "$(\ls $AGNO_SOURCE 2>/dev/null)" ]; then
	cp -fR $AGNO_SOURCE/* $AGNO_WORK
	cd $AGNO_WORK
	$AGNO_HOME/unboop *
fi

# run build function
cd $AGNO_WORK
agno_build

# gotta install that shiz diz
cd $AGNO_WORK
agno_install

# let's make a package out of the result
cd $AGNO_DESTDIR
tar -czvf $AGNO_PACKAGES/$PKGNAME.tar.gz .

# we're done! let's cleanup
rm -rf $AGNO_WORK $AGNO_DESTDIR

# notice
echo "Built '$PKGNAME' successfully (i.e. without errors)"
