#!/bin/sh -e

if [ ! -e "$1" ]; then
	echo "ERROR: Provided package file doesn't exist!"
	exit 1
fi

# get our vars
. $HOME/agno/agnorc || exit 1

PKGFILE=$(basename "$1")
PKGNAME=$(echo $PKGFILE | cut -d\# -f1)

# re-define var
AGNO_WORK=$AGNO_WORK/$PKGFILE

# uninstall package if it already exists
if \ls -1 $AGNO_META | grep -q $PKGNAME; then
	echo "Deleting previously installed package of same name."
	$AGNO_HOME/agno_rm $PKGNAME
fi

# untar package so we can work with files
rm -rf $AGNO_WORK
mkdir -p $AGNO_WORK
cp "$1" "$AGNO_WORK"
cd $AGNO_WORK
tar xzvf $PKGFILE

# copy usr dir, which should contain everything
if [ ! -d usr ]; then
	echo "ERROR: There is no usr/ dir in package."
	exit 1
fi
rsync -av usr/ $AGNO_USR

# fill meta data about new package
find usr/ -type f > $AGNO_META/$PKGNAME

# cleanup
rm -rf $AGNO_WORK

# notice
echo "Installed '$1' successfully (i.e. without errors)"
