#!/bin/sh -e

# get our vars
. $HOME/agno/agnorc || exit 1

PKGFILE="$(basename $1)"
PKGNAME="$(echo $PKGFILE | cut -d# -f1)"

# untar package so we can work with files
mkdir -p $AGNO_WORK
cp "$1" "$AGNO_WORK"
cd $AGNO_WORK
tar xzvf $PKGFILE

# copy usr dir, which should contain everything
rsync -av usr/ $AGNO_USR

# fill meta data about new package
find usr/ -type f > $AGNO_META/$PKGNAME

# cleanup
rm -rf $AGNO_WORK

# notice
echo "Installed '$1' successfully (i.e. without errors)"
