#!/bin/sh -e

# get vars
. $HOME/agno/agnorc || exit 1

# find package name in a lot of kinds of strings
PKGNAME=$(basename "$1" | cut -d\# -f1)

# delete all of the package's files
cd $AGNO_HOME
while read line; do
	rm -f "$line"
done < $AGNO_META/$PKGNAME

# no longer necessary
rm $AGNO_META/$PKGNAME

# notice
echo "Uninstalled '$1' successfully (i.e. without errors)"
